on:
  workflow_dispatch:
  
name: Kernel
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: manual
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
          arch: [armv6,armv7,aarch64,amd64,s390x,ppc64le,mips64le,i386]
          distro: [bullseye]
          include:
            - arch: riscv64
              distro: unstable
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Download artifact
      #  uses: GarnetOS/action-download-artifact@test10
      #  with:
      #    workflow: kernel-multiarch.yml
      #    name: kernel-${{ matrix.arch }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: GarnetOS/run-on-arch-action@v2.1.2
        name: Prepare
        with: 
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          shell: /bin/sh
          setup: |
            mkdir -p "${PWD}/linux-5.10.17-${{ matrix.arch }}"
          dockerRunArgs: |
           --volume "${PWD}/linux-5.10.17-${{ matrix.arch }}:/linux-5.10.17-${{ matrix.arch }}"
          install: |
            apt-get update
            apt-get install -y libncurses-dev sudo wget xz-utils gcc g++ make flex bison libssl-dev libelf-dev build-essential timelimit bc kmod cpio 
          run: |
            wget https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.10.17.tar.xz
            tar -xf linux-5.10.17.tar.xz
            mv linux-5.10.17/*  linux-5.10.17-${{ matrix.arch }}/
            cd linux-5.10.17-${{ matrix.arch }}
            ls
            make mrproper
            #wget https://gist.githubusercontent.com/radimkohout/e59440d3a06a763d26e1ca43ce9dd258/raw/b0266d6cbfaa40cf3cdd576d9d4e1e613115f305/.config
            make defconfig
           
      - uses: GarnetOS/run-on-arch-action@v2.1.2
        name: Make 1 - ${{ matrix.arch }}
        with: 
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          shell: /bin/sh
          dockerRunArgs: |
           --volume "${PWD}/linux-5.10.17-${{ matrix.arch }}:/linux-5.10.17-${{ matrix.arch }}"
          install: |
            apt-get update
            apt-get install -y libncurses-dev sudo wget xz-utils gcc g++ make flex bison libssl-dev libelf-dev build-essential timelimit bc kmod cpio 
          run: |
            cd linux-5.10.17-${{ matrix.arch }}
            timelimit -q -t 18900 make || true
      - uses: actions/upload-artifact@v2
        with:
          name: kernel-${{ matrix.arch }}
          path: linux-5.10.17-${{ matrix.arch }}
            
