on:
  workflow_dispatch:
  
name: Kernel
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: manual
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: buster
          - arch: ppc64le
            distro: buster
          - arch: s390x
            distro: buster
          - arch: armv6
            distro: buster
          - arch: armv7
            distro: buster
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/cache@v2.1.6
        name: Restore cache
        with:
          path: linux-5.10.17-${{ matrix.arch }}
          key: kernel - ${{ matrix.arch }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Prepare
        with: 
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          shell: /bin/sh
          setup: |
            mkdir -p "${PWD}/linux-5.10.17-${{ matrix.arch }}"
          dockerRunArgs: |
           --volume "${PWD}/linux-5.10.17-${{ matrix.arch }}:/linux-5.10.17-${{ matrix.arch }}"
          install: |
            apt-get update
            apt-get install -y libncurses-dev sudo wget xz-utils gcc g++ make flex bison libssl-dev libelf-dev build-essential timelimit
          run: |
            wget https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.10.17.tar.xz
            tar -xf linux-5.10.17.tar.xz
            mv linux-5.10.17  linux-5.10.17-${{ matrix.arch }}
            cd linux-5.10.17-${{ matrix.arch }}
            ls
            make mrproper
            wget https://gist.githubusercontent.com/radimkohout/e59440d3a06a763d26e1ca43ce9dd258/raw/b0266d6cbfaa40cf3cdd576d9d4e1e613115f305/.config
           
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Make 1 - ${{ matrix.arch }}
        with: 
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          shell: /bin/sh
          dockerRunArgs: |
           --volume "${PWD}/linux-5.10.17-${{ matrix.arch }}:/linux-5.10.17-${{ matrix.arch }}"
          install: |
            apt-get update
            apt-get install -y libncurses-dev sudo wget xz-utils gcc g++ make flex bison libssl-dev libelf-dev build-essential timelimit
          run: |
            cd linux-5.10.17-${{ matrix.arch }}
            timelimit -q -t 1200 make || true
            
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Make 2 - ${{ matrix.arch }}
        with: 
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          shell: /bin/sh
          dockerRunArgs: |
           --volume "${PWD}/linux-5.10.17-${{ matrix.arch }}:/linux-5.10.17-${{ matrix.arch }}"
          install: |
            apt-get update
            apt-get install -y libncurses-dev sudo wget xz-utils gcc g++ make flex bison libssl-dev libelf-dev build-essential timelimit
            cd linux-5.10.17-${{ matrix.arch }}
          run: |
            timelimit -q -t 1200 make || true         
