name: Kernel
 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: buster
          - arch: ppc64le
            distro: buster
          - arch: s390x
            distro: buster
          - arch: armv6
            distro: buster
          - arch: armv7
            distro: buster
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Prepare
        with: 
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          shell: /bin/sh
          install: |
            apt-get update
            apt-get install -y libncurses-dev sudo wget xz-utils gcc g++ make flex bison libssl-dev libelf-dev build-essential
          run: |
            wget https://www.kernel.org/pub/linux/kernel/v5.x/linux-5.10.17.tar.xz
            tar -xvf linux-5.10.17.tar.xz
            cd linux-5.10.17
            make mrproper
            wget https://gist.githubusercontent.com/radimkohout/e59440d3a06a763d26e1ca43ce9dd258/raw/b0266d6cbfaa40cf3cdd576d9d4e1e613115f305/.config
            timelimit -q -t 1200 make
            #make modules_install
